### ISSUE TITLE
Removing packages

### ISSUE THREAD

**Issue by rennis250** [JuliaLang/METADATA.jl#11200]
I would like to remove my packages from METADATA.jl. I submitted them years ago and have barely worked on them since. I don't have the time or interest to keep up with them and I'm quite certain that barely anyone uses them. The following packages are what I would like to remove:

- Sparrow.jl
- Processing.jl
- SDL.jl
- Tealeaf.jl (may not actually be in METADATA, but I can't remember...)
- Willow.jl (may not actually be in METADATA, but I can't remember...)
- Arduino.jl (provides almost no functionality)
- GLUT.jl
- OpenGL.jl (not even my package, really. modified from something Jasper den Ouden had made)
- GetC.jl (may not actually be in METADATA, but I can't remember... not even my package, really. modified from something Jasper den Ouden had made)

**Comment by tkelman** [comment]
Packages shouldn't be completely removed in case anyone was depending on them, but they can be deprecated. Arduino, GetC, GLUT, OpenGL, and SDL were already deprecated in https://github.com/JuliaLang/METADATA.jl/pull/9048 since none of them load on Julia 0.6.

Processing never had a release version tagged, so nothing to do there. Tealeaf and Willow were never registered. That leaves just Sparrow. But since the only release Sparrow depends on Color.jl, and Color.jl was deprecated in https://github.com/JuliaLang/METADATA.jl/commit/474b51a5d6fe63140fa759f54bddc7497d567bda, Sparrow is effectively already deprecated too. So I don't think you have to do anything here. If you want to completely delete your copies of the repositories, it would be best to first redirect the url files to point to JuliaPackageMirrors.

**Comment by rennis250** [comment]
Thanks for the info. I opened a Pull Request in #11911 .

**Comment by PallHaraldsson** [comment]
"were already deprecated in #9048 since none of them load on Julia 0.6."

Interesting you can do that. If anyone wants to take over development, I guess it's possible (only with permission of [here] @rennis250; or would you say all are reduntant, e.g. SDL with other (non-SDL-based) better packages? Or don't you just have time?).

After some time, can a name be reclaim for a new package?

**Comment by rennis250** [comment]
@tkelman
