### ISSUE TITLE
Can publish due to `DiffEqDevTools v0.7.0 – no valid versions exist for package DiffBase`

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/METADATA.jl#12139]
I'm getting the following error while trying to tag and publish a new package:
```julia
julia> PkgDev.publish()
INFO: Validating METADATA
ERROR: packages with unsatisfiable requirements found:
    DiffEqDevTools v0.7.0 – no valid versions exist for package DiffBase
    DiffEqDevTools v0.7.1 – no valid versions exist for package DiffBase
```

**Comment by carlobaldassi** [comment]
Could you please tell me
1. What was your METADATA commit
2. What was the change that you were trying to publish

Thanks

**Comment by ChrisRackauckas** [comment]
Hmm, things to note:

1. DiffEqDevTools doesn't depend on DiffBase, nor the other way around, nor indirectly.
2. This doesn't seem to happen with normal `Pkg.update()`s, so it's a publishing-only problem?
3. There was a recent change in the DiffEq ecosystem where a bunch of packages updated to be compatible with the newest ForwardDiff.jl (v0.7.0). That means that just recently none of DiffEq depends on DiffBase.jl anymore at all because of 
https://github.com/JuliaDiff/ForwardDiff.jl/commit/1129f9be2b706e52a430d5b29f7ddf41bb49ca18#diff-58476995b642435595799e856c5d2a74 . Whatever is going on could be related to versioning issues with this?
4. (3) is slightly off because NLsolve.jl depends on DiffBase.jl still

```julia
julia> Pkg.dependents("DiffBase")
3-element Array{AbstractString,1}:
 "Celeste"
 "NLsolve"
 "Klara"
```

and it is a dependency of OrdinaryDiffEq.jl, but not DiffEqDevTools.jl. But now that https://github.com/JuliaNLSolvers/NLsolve.jl/pull/131 is merged, NLsolve.jl will soon tag to make that no longer true. 

5. None of DiffEq relates to Celeste or Klara. So we should check if this still exists after the NLsolve.jl tag and if it does, there's something really weird with versioning going on.

Hopefully that information helps.

**Comment by carlobaldassi** [comment]
It seems, from a few quick experiments I did, that this problem should go away by setting

```
ENV["JULIA_PKGRESOLVE_ACCURACY"]=2
```

I will see if I can get a more satisfactory fix. @dlfivefifty, can you check if this works in the meanwhile?


> This doesn't seem to happen with normal `Pkg.update()`s, so it's a publishing-only problem?

Yes, these errors are produced by `PkgDev.Entry.check_metadata()`.

**Comment by dlfivefifty** [comment]
Yes that worked:

https://github.com/JuliaLang/METADATA.jl/pull/12156

**Comment by andreasnoack** [comment]
Can this be closed?
