### ISSUE TITLE
The one cycle in requires

### ISSUE THREAD

**Issue by IainNZ** [JuliaLang/METADATA.jl#2535]
May be of interest to @tkelman and @amitmurthy:

WinRPM requires HTTPClient on `@unix`
HTTPClient requires LibCURL
LibCURL requires WinRPM on `@windows`

So, there isn't actually an issue because of the platform flags, but still, thought it was of interest. Only detected because my METADATA analysis code just ignores those platform flags.

**Comment by tkelman** [comment]
Is this actually an issue? I both created this cycle (https://github.com/JuliaWeb/LibCURL.jl/pull/10) by getting LibCURL to work on Windows by using WinRPM, then later broke it (https://github.com/JuliaLang/WinRPM.jl/pull/29) by making WinRPM only depend on LibCURL on Unix. It resulted in some extra needless downloading of winrpm repodata while there was a cycle, but otherwise didn't seem to matter. At the moment you can't have Pkg without Git and you can't have Git without curl, but on Windows we needed a 64 bit libcurl dll for 64 bit Julia whereas the command-line Git (and its included curl) in the Windows binaries is only 32 bit.

**Comment by IainNZ** [comment]
> So, there isn't actually an issue because of the platform flags, but still, thought it was of interest.

Just-for-fun "issue", was curious where it came from :+1:

**Comment by tkelman** [comment]
k, now you know

**Comment by tkelman** [comment]
There may still be a bug in either Pkg or the way I did things in one of the packages in that I see "Building LibCURL" a little too frequently, but it never bothered me enough to track down why it was happening.

**Comment by carlobaldassi** [comment]
Just adding some info which may not be generally known here, even if it doesn't apply to this case because of the OS flags.
The package manager is in principle able to handle cycles (this situation is even [routinely tested](https://github.com/JuliaLang/julia/blob/ed61f1e56d9ed9cda8825e82a5f26922f5b05811/test/resolve.jl#L174)). However, the solver is heuristic, and cycles make things more difficult, so they are in fact better avoided whenever possible (besides the fact that circular dependencies probably signal something wrong in the first place).
