### ISSUE TITLE
Deprecate PValueAdjust.jl in favor of MultipleTesting.jl

### ISSUE THREAD

**Issue by dirkschumacher** [JuliaLang/METADATA.jl#7140]
2 years ago I wrote a small package [PValueAdjust.jl](https://github.com/dirkschumacher/PValueAdjust.jl) that implemented some simple p-value adjustment methods for multiple testing. The recent MultipleTesting.jl package implements all the methods that are in PValueAdjust.jl and many more (and is actively maintained). In addition, PValueAdjust.jl now also seems to cause problems with Julia 0.5.

I would like to deprecate PValueAdjust.jl and point users to that new package. Should I send a pullrequest to remove PValueAdjust.jl from METADATA.jl? I already added a note to the package README pointing new users to MultipleTesting.jl.

**Comment by aviks** [comment]
Removing a package will cause issues for users who have existing installs. The reccomended way to deprecate a package is to add the current released julia version as the maximum in the package's requirements. Then, the package cannot be installed in future versions of julia. So add a `julia 0.3 0.5` line in the `requires` file of every version in METADATA. You'll have to make a PR to METADATA.jl by hand, since the `Pkg` tools will be unable to do this automatically.

**Comment by dirkschumacher** [comment]
Ok thanks. Will do that then.
