### ISSUE TITLE
CLRF -> LF endings problem with METADATA

### ISSUE THREAD

**Issue by tlnagy** [JuliaLang/METADATA.jl#8985]
Is anyone else seeing the following warning on METADATA master?

```
warning: CRLF will be replaced by LF in DynamicalBilliardsPlotting/versions/0.1.0/requires.
The file will have its original line endings in your working directory.
```

I can't seem to get rid of this warning.

**Comment by carlobaldassi** [comment]
This happened with DynamicalBilliards too, in 8af0aa4f9523f9a627c1a3e0a2f217bb931db124, see #8964.
It can become annoying when working with METADATA because it can cause git to refuse to perform some operations, e.g. rebasing. I also couldn't find a way to disable it.

cc @Datseris: maybe you have a non standard git config setting for core.autocrlf?

**Comment by Datseris** [comment]
Unfortunately I did not find something weird... the setting for core.autoconfig was true (which I think is the correct one?)

I run the command `git config --global core.autocrlf  true` in my git terminal. I hope it will do the trick. 

I have recently switched to using gitkraken  for my work,  maybe I need to configure  something there as well?

**Comment by ChrisRackauckas** [comment]
>I have recently switched to using gitkraken for my work, maybe I need to configure something there as well?

I've never had this problem with GitKraken. And it should respect your global git settings anyways.
